version: '3'

networks:
  voip-net:
    name: voip-net
    ipam:
      config:
        - subnet: 10.9.0.0/24
services:
  voip-server:
    image: mlan/asterisk
    container_name: voip-server
    networks:
      voip-net:
        ipv4_address: 10.9.0.4                  # Only here to help
    cap_add:
      - sys_ptrace                          # Only here to help testing
      - net_admin                           # Allow NFT, used by AutoBan
      - net_raw                             # Allow NFT, used by AutoBan
    ports:
      - "${SMS_PORT-8080}:${WEBSMSD_PORT:-80}" # WEBSMSD port mapping
      - "5060:5060/udp"                     # SIP UDP port
      - "5060:5060"                         # SIP TCP port
      - "5061:5061"                         # SIP TLS port
      - "10000-10099:10000-10099/udp"       # RTP ports
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}      # Logging
      - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
      - PULSE_SERVER=unix:/run/pulse/socket # Use host audio
      - PULSE_COOKIE=/run/pulse/cookie      # Use host audio
      - WEBSMSD_PORT=${WEBSMSD_PORT-80}     # WEBSMSD internal port
    volumes:
      - tele-conf:/srv                      # Persistent storage
      - ./pulse:/run/pulse:rshared          # Use host audio
      - /etc/localtime:/etc/localtime:ro    # Use host timezone

  client1:
    build:
      context: .
      dockerfile: Dockerfile
    image: large
    container_name: client1
    networks:
      voip-net:
        ipv4_address: 10.9.0.3
    environment:
      - PULSE_SERVER=unix:/run/pulse/socket
    volumes:
      - ./client-config:/config
    privileged: true
    tty: true
    command: /bin/bash -c "apt-get update && apt-get install -y inetutils-ping && /bin/bash"

  client2:
    build:
      context: .
      dockerfile: Dockerfile
    image: large
    container_name: client2
    networks:
      voip-net:
        ipv4_address: 10.9.0.2
    environment:
      - PULSE_SERVER=unix:/run/pulse/socket
    volumes:
      - ./client-config:/config
    tty: true
    privileged: true
    command: /bin/bash -c "apt-get update && apt-get install -y inetutils-ping && /bin/bash"

  attacker:
    build:
      context: .
      dockerfile: Dockerfile
    image: large
    container_name: attacker
    networks:
      voip-net:
        ipv4_address: 10.9.0.5
    privileged: true
    volumes:
      - ./attacker-files:/attacker-files   # Shared folder for file transfer
    tty: true
    command: /bin/bash -c "apt-get update && apt-get install -y inetutils-ping && /bin/bash"
    
    
volumes:
  tele-conf:
    driver: local



